"""Unit tests for metadata.csv and cross-validation fold assignments."""

from pathlib import Path

import pandas as pd
import pytest

from medcomp.config import METADATA_CSV_PATH


@pytest.fixture(scope="module")
def metadata_df() -> pd.DataFrame:
    """Load the metadata.csv file generated by scripts/build_metadata.py."""
    if not METADATA_CSV_PATH.exists():
        # Generate on the fly if not already run
        from scripts.build_metadata import build_metadata
        return build_metadata()
    return pd.read_csv(METADATA_CSV_PATH)


def test_every_image_has_label(metadata_df: pd.DataFrame):
    """Every image must have a valid non-null label."""
    assert not metadata_df["label"].isna().any()
    assert len(metadata_df) == 138


def test_labels_are_only_0_or_1(metadata_df: pd.DataFrame):
    """Labels must strictly belong to {0, 1} (0=Normal, 1=TB)."""
    unique_labels = set(metadata_df["label"].unique())
    assert unique_labels == {0, 1}


def test_no_stem_in_more_than_one_fold(metadata_df: pd.DataFrame):
    """Each unique stem must be assigned to exactly one cross-validation fold."""
    assert metadata_df["stem"].nunique() == len(metadata_df)
    # Check that each stem only maps to 1 fold
    stem_fold_counts = metadata_df.groupby("stem")["fold"].nunique()
    assert (stem_fold_counts == 1).all()


def test_each_fold_contains_both_classes(metadata_df: pd.DataFrame):
    """Every fold must contain both Normal (0) and TB (1) samples."""
    for f in range(5):
        fold_samples = metadata_df[metadata_df["fold"] == f]
        labels_in_fold = set(fold_samples["label"].unique())
        assert labels_in_fold == {0, 1}, f"Fold {f} does not contain both classes: {labels_in_fold}"


def test_fold_sizes_differ_by_at_most_1(metadata_df: pd.DataFrame):
    """Fold sizes must be balanced, differing by at most 1 sample."""
    fold_sizes = metadata_df["fold"].value_counts().tolist()
    assert len(fold_sizes) == 5
    max_diff = max(fold_sizes) - min(fold_sizes)
    assert max_diff <= 1, f"Fold sizes differ by {max_diff}: {fold_sizes}"


def test_patient_id_consistency_across_folds(metadata_df: pd.DataFrame):
    """No single patient_id should ever leak across multiple validation folds."""
    patient_fold_counts = metadata_df.groupby("patient_id")["fold"].nunique()
    assert (patient_fold_counts == 1).all()


def test_roi_fraction_and_shapes(metadata_df: pd.DataFrame):
    """ROI fraction must be between 0 and 1, and shapes must be well-formed strings."""
    assert (metadata_df["roi_fraction"] > 0.0).all()
    assert (metadata_df["roi_fraction"] < 1.0).all()
    assert metadata_df["original_shape"].str.startswith("(").all()
    assert metadata_df["original_shape"].str.endswith(")").all()
